# CMake generated Testfile for 
# Source directory: F:/opengl/glm/test/core
# Build directory: F:/opengl/glm/test/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_cast "F:/opengl/glm/test/core/Debug/test-core_type_cast.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_cast "F:/opengl/glm/test/core/Release/test-core_type_cast.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_cast "F:/opengl/glm/test/core/MinSizeRel/test-core_type_cast.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_cast "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_cast.exe")
else()
  add_test(test-core_type_cast NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_float "F:/opengl/glm/test/core/Debug/test-core_type_float.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_float "F:/opengl/glm/test/core/Release/test-core_type_float.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_float "F:/opengl/glm/test/core/MinSizeRel/test-core_type_float.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_float "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_float.exe")
else()
  add_test(test-core_type_float NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_int "F:/opengl/glm/test/core/Debug/test-core_type_int.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_int "F:/opengl/glm/test/core/Release/test-core_type_int.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_int "F:/opengl/glm/test/core/MinSizeRel/test-core_type_int.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_int "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_int.exe")
else()
  add_test(test-core_type_int NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_length "F:/opengl/glm/test/core/Debug/test-core_type_length.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_length "F:/opengl/glm/test/core/Release/test-core_type_length.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_length "F:/opengl/glm/test/core/MinSizeRel/test-core_type_length.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_length "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_length.exe")
else()
  add_test(test-core_type_length NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_length_size "F:/opengl/glm/test/core/Debug/test-core_type_length_size.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_length_size "F:/opengl/glm/test/core/Release/test-core_type_length_size.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_length_size "F:/opengl/glm/test/core/MinSizeRel/test-core_type_length_size.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_length_size "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_length_size.exe")
else()
  add_test(test-core_type_length_size NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat2x2 "F:/opengl/glm/test/core/Debug/test-core_type_mat2x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat2x2 "F:/opengl/glm/test/core/Release/test-core_type_mat2x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat2x2 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat2x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat2x2 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat2x2.exe")
else()
  add_test(test-core_type_mat2x2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat2x3 "F:/opengl/glm/test/core/Debug/test-core_type_mat2x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat2x3 "F:/opengl/glm/test/core/Release/test-core_type_mat2x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat2x3 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat2x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat2x3 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat2x3.exe")
else()
  add_test(test-core_type_mat2x3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat2x4 "F:/opengl/glm/test/core/Debug/test-core_type_mat2x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat2x4 "F:/opengl/glm/test/core/Release/test-core_type_mat2x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat2x4 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat2x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat2x4 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat2x4.exe")
else()
  add_test(test-core_type_mat2x4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat3x2 "F:/opengl/glm/test/core/Debug/test-core_type_mat3x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat3x2 "F:/opengl/glm/test/core/Release/test-core_type_mat3x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat3x2 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat3x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat3x2 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat3x2.exe")
else()
  add_test(test-core_type_mat3x2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat3x3 "F:/opengl/glm/test/core/Debug/test-core_type_mat3x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat3x3 "F:/opengl/glm/test/core/Release/test-core_type_mat3x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat3x3 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat3x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat3x3 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat3x3.exe")
else()
  add_test(test-core_type_mat3x3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat3x4 "F:/opengl/glm/test/core/Debug/test-core_type_mat3x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat3x4 "F:/opengl/glm/test/core/Release/test-core_type_mat3x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat3x4 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat3x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat3x4 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat3x4.exe")
else()
  add_test(test-core_type_mat3x4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat4x2 "F:/opengl/glm/test/core/Debug/test-core_type_mat4x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat4x2 "F:/opengl/glm/test/core/Release/test-core_type_mat4x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat4x2 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat4x2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat4x2 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat4x2.exe")
else()
  add_test(test-core_type_mat4x2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat4x3 "F:/opengl/glm/test/core/Debug/test-core_type_mat4x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat4x3 "F:/opengl/glm/test/core/Release/test-core_type_mat4x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat4x3 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat4x3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat4x3 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat4x3.exe")
else()
  add_test(test-core_type_mat4x3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat4x4 "F:/opengl/glm/test/core/Debug/test-core_type_mat4x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat4x4 "F:/opengl/glm/test/core/Release/test-core_type_mat4x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat4x4 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_mat4x4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat4x4 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_mat4x4.exe")
else()
  add_test(test-core_type_mat4x4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_vec1 "F:/opengl/glm/test/core/Debug/test-core_type_vec1.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_vec1 "F:/opengl/glm/test/core/Release/test-core_type_vec1.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_vec1 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_vec1.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_vec1 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_vec1.exe")
else()
  add_test(test-core_type_vec1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_vec2 "F:/opengl/glm/test/core/Debug/test-core_type_vec2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_vec2 "F:/opengl/glm/test/core/Release/test-core_type_vec2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_vec2 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_vec2.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_vec2 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_vec2.exe")
else()
  add_test(test-core_type_vec2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_vec3 "F:/opengl/glm/test/core/Debug/test-core_type_vec3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_vec3 "F:/opengl/glm/test/core/Release/test-core_type_vec3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_vec3 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_vec3.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_vec3 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_vec3.exe")
else()
  add_test(test-core_type_vec3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_vec4 "F:/opengl/glm/test/core/Debug/test-core_type_vec4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_vec4 "F:/opengl/glm/test/core/Release/test-core_type_vec4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_vec4 "F:/opengl/glm/test/core/MinSizeRel/test-core_type_vec4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_vec4 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_type_vec4.exe")
else()
  add_test(test-core_type_vec4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_common "F:/opengl/glm/test/core/Debug/test-core_func_common.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_common "F:/opengl/glm/test/core/Release/test-core_func_common.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_common "F:/opengl/glm/test/core/MinSizeRel/test-core_func_common.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_common "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_common.exe")
else()
  add_test(test-core_func_common NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_exponential "F:/opengl/glm/test/core/Debug/test-core_func_exponential.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_exponential "F:/opengl/glm/test/core/Release/test-core_func_exponential.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_exponential "F:/opengl/glm/test/core/MinSizeRel/test-core_func_exponential.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_exponential "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_exponential.exe")
else()
  add_test(test-core_func_exponential NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_geometric "F:/opengl/glm/test/core/Debug/test-core_func_geometric.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_geometric "F:/opengl/glm/test/core/Release/test-core_func_geometric.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_geometric "F:/opengl/glm/test/core/MinSizeRel/test-core_func_geometric.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_geometric "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_geometric.exe")
else()
  add_test(test-core_func_geometric NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_integer "F:/opengl/glm/test/core/Debug/test-core_func_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_integer "F:/opengl/glm/test/core/Release/test-core_func_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_integer "F:/opengl/glm/test/core/MinSizeRel/test-core_func_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_integer "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_integer.exe")
else()
  add_test(test-core_func_integer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_integer_bit_count "F:/opengl/glm/test/core/Debug/test-core_func_integer_bit_count.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_integer_bit_count "F:/opengl/glm/test/core/Release/test-core_func_integer_bit_count.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_integer_bit_count "F:/opengl/glm/test/core/MinSizeRel/test-core_func_integer_bit_count.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_integer_bit_count "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_integer_bit_count.exe")
else()
  add_test(test-core_func_integer_bit_count NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_integer_find_lsb "F:/opengl/glm/test/core/Debug/test-core_func_integer_find_lsb.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_integer_find_lsb "F:/opengl/glm/test/core/Release/test-core_func_integer_find_lsb.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_integer_find_lsb "F:/opengl/glm/test/core/MinSizeRel/test-core_func_integer_find_lsb.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_integer_find_lsb "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_integer_find_lsb.exe")
else()
  add_test(test-core_func_integer_find_lsb NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_integer_find_msb "F:/opengl/glm/test/core/Debug/test-core_func_integer_find_msb.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_integer_find_msb "F:/opengl/glm/test/core/Release/test-core_func_integer_find_msb.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_integer_find_msb "F:/opengl/glm/test/core/MinSizeRel/test-core_func_integer_find_msb.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_integer_find_msb "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_integer_find_msb.exe")
else()
  add_test(test-core_func_integer_find_msb NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_matrix "F:/opengl/glm/test/core/Debug/test-core_func_matrix.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_matrix "F:/opengl/glm/test/core/Release/test-core_func_matrix.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_matrix "F:/opengl/glm/test/core/MinSizeRel/test-core_func_matrix.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_matrix "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_matrix.exe")
else()
  add_test(test-core_func_matrix NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_noise "F:/opengl/glm/test/core/Debug/test-core_func_noise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_noise "F:/opengl/glm/test/core/Release/test-core_func_noise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_noise "F:/opengl/glm/test/core/MinSizeRel/test-core_func_noise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_noise "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_noise.exe")
else()
  add_test(test-core_func_noise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_packing "F:/opengl/glm/test/core/Debug/test-core_func_packing.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_packing "F:/opengl/glm/test/core/Release/test-core_func_packing.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_packing "F:/opengl/glm/test/core/MinSizeRel/test-core_func_packing.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_packing "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_packing.exe")
else()
  add_test(test-core_func_packing NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_trigonometric "F:/opengl/glm/test/core/Debug/test-core_func_trigonometric.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_trigonometric "F:/opengl/glm/test/core/Release/test-core_func_trigonometric.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_trigonometric "F:/opengl/glm/test/core/MinSizeRel/test-core_func_trigonometric.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_trigonometric "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_trigonometric.exe")
else()
  add_test(test-core_func_trigonometric NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_vector_relational "F:/opengl/glm/test/core/Debug/test-core_func_vector_relational.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_vector_relational "F:/opengl/glm/test/core/Release/test-core_func_vector_relational.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_vector_relational "F:/opengl/glm/test/core/MinSizeRel/test-core_func_vector_relational.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_vector_relational "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_vector_relational.exe")
else()
  add_test(test-core_func_vector_relational NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_swizzle "F:/opengl/glm/test/core/Debug/test-core_func_swizzle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_swizzle "F:/opengl/glm/test/core/Release/test-core_func_swizzle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_swizzle "F:/opengl/glm/test/core/MinSizeRel/test-core_func_swizzle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_swizzle "F:/opengl/glm/test/core/RelWithDebInfo/test-core_func_swizzle.exe")
else()
  add_test(test-core_func_swizzle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_setup_force_cxx98 "F:/opengl/glm/test/core/Debug/test-core_setup_force_cxx98.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_setup_force_cxx98 "F:/opengl/glm/test/core/Release/test-core_setup_force_cxx98.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_setup_force_cxx98 "F:/opengl/glm/test/core/MinSizeRel/test-core_setup_force_cxx98.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_setup_force_cxx98 "F:/opengl/glm/test/core/RelWithDebInfo/test-core_setup_force_cxx98.exe")
else()
  add_test(test-core_setup_force_cxx98 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_setup_message "F:/opengl/glm/test/core/Debug/test-core_setup_message.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_setup_message "F:/opengl/glm/test/core/Release/test-core_setup_message.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_setup_message "F:/opengl/glm/test/core/MinSizeRel/test-core_setup_message.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_setup_message "F:/opengl/glm/test/core/RelWithDebInfo/test-core_setup_message.exe")
else()
  add_test(test-core_setup_message NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_setup_precision "F:/opengl/glm/test/core/Debug/test-core_setup_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_setup_precision "F:/opengl/glm/test/core/Release/test-core_setup_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_setup_precision "F:/opengl/glm/test/core/MinSizeRel/test-core_setup_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_setup_precision "F:/opengl/glm/test/core/RelWithDebInfo/test-core_setup_precision.exe")
else()
  add_test(test-core_setup_precision NOT_AVAILABLE)
endif()
