# CMake generated Testfile for 
# Source directory: F:/opengl/glm/test/gtc
# Build directory: F:/opengl/glm/test/gtc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_bitfield "F:/opengl/glm/test/gtc/Debug/test-gtc_bitfield.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_bitfield "F:/opengl/glm/test/gtc/Release/test-gtc_bitfield.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_bitfield "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_bitfield.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_bitfield "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_bitfield.exe")
else()
  add_test(test-gtc_bitfield NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_constants "F:/opengl/glm/test/gtc/Debug/test-gtc_constants.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_constants "F:/opengl/glm/test/gtc/Release/test-gtc_constants.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_constants "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_constants.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_constants "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_constants.exe")
else()
  add_test(test-gtc_constants NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_epsilon "F:/opengl/glm/test/gtc/Debug/test-gtc_epsilon.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_epsilon "F:/opengl/glm/test/gtc/Release/test-gtc_epsilon.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_epsilon "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_epsilon.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_epsilon "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_epsilon.exe")
else()
  add_test(test-gtc_epsilon NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_integer "F:/opengl/glm/test/gtc/Debug/test-gtc_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_integer "F:/opengl/glm/test/gtc/Release/test-gtc_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_integer "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_integer "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_integer.exe")
else()
  add_test(test-gtc_integer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_access "F:/opengl/glm/test/gtc/Debug/test-gtc_matrix_access.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_access "F:/opengl/glm/test/gtc/Release/test-gtc_matrix_access.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_access "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_matrix_access.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_access "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_matrix_access.exe")
else()
  add_test(test-gtc_matrix_access NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_integer "F:/opengl/glm/test/gtc/Debug/test-gtc_matrix_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_integer "F:/opengl/glm/test/gtc/Release/test-gtc_matrix_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_integer "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_matrix_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_integer "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_matrix_integer.exe")
else()
  add_test(test-gtc_matrix_integer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_inverse "F:/opengl/glm/test/gtc/Debug/test-gtc_matrix_inverse.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_inverse "F:/opengl/glm/test/gtc/Release/test-gtc_matrix_inverse.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_inverse "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_matrix_inverse.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_inverse "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_matrix_inverse.exe")
else()
  add_test(test-gtc_matrix_inverse NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_transform "F:/opengl/glm/test/gtc/Debug/test-gtc_matrix_transform.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_transform "F:/opengl/glm/test/gtc/Release/test-gtc_matrix_transform.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_transform "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_matrix_transform.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_transform "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_matrix_transform.exe")
else()
  add_test(test-gtc_matrix_transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_noise "F:/opengl/glm/test/gtc/Debug/test-gtc_noise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_noise "F:/opengl/glm/test/gtc/Release/test-gtc_noise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_noise "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_noise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_noise "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_noise.exe")
else()
  add_test(test-gtc_noise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_packing "F:/opengl/glm/test/gtc/Debug/test-gtc_packing.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_packing "F:/opengl/glm/test/gtc/Release/test-gtc_packing.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_packing "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_packing.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_packing "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_packing.exe")
else()
  add_test(test-gtc_packing NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_quaternion "F:/opengl/glm/test/gtc/Debug/test-gtc_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_quaternion "F:/opengl/glm/test/gtc/Release/test-gtc_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_quaternion "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_quaternion "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_quaternion.exe")
else()
  add_test(test-gtc_quaternion NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_random "F:/opengl/glm/test/gtc/Debug/test-gtc_random.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_random "F:/opengl/glm/test/gtc/Release/test-gtc_random.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_random "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_random.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_random "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_random.exe")
else()
  add_test(test-gtc_random NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_round "F:/opengl/glm/test/gtc/Debug/test-gtc_round.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_round "F:/opengl/glm/test/gtc/Release/test-gtc_round.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_round "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_round.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_round "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_round.exe")
else()
  add_test(test-gtc_round NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_reciprocal "F:/opengl/glm/test/gtc/Debug/test-gtc_reciprocal.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_reciprocal "F:/opengl/glm/test/gtc/Release/test-gtc_reciprocal.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_reciprocal "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_reciprocal.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_reciprocal "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_reciprocal.exe")
else()
  add_test(test-gtc_reciprocal NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_type_precision "F:/opengl/glm/test/gtc/Debug/test-gtc_type_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_type_precision "F:/opengl/glm/test/gtc/Release/test-gtc_type_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_type_precision "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_type_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_type_precision "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_type_precision.exe")
else()
  add_test(test-gtc_type_precision NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_type_ptr "F:/opengl/glm/test/gtc/Debug/test-gtc_type_ptr.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_type_ptr "F:/opengl/glm/test/gtc/Release/test-gtc_type_ptr.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_type_ptr "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_type_ptr.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_type_ptr "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_type_ptr.exe")
else()
  add_test(test-gtc_type_ptr NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_ulp "F:/opengl/glm/test/gtc/Debug/test-gtc_ulp.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_ulp "F:/opengl/glm/test/gtc/Release/test-gtc_ulp.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_ulp "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_ulp.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_ulp "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_ulp.exe")
else()
  add_test(test-gtc_ulp NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_vec1 "F:/opengl/glm/test/gtc/Debug/test-gtc_vec1.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_vec1 "F:/opengl/glm/test/gtc/Release/test-gtc_vec1.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_vec1 "F:/opengl/glm/test/gtc/MinSizeRel/test-gtc_vec1.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_vec1 "F:/opengl/glm/test/gtc/RelWithDebInfo/test-gtc_vec1.exe")
else()
  add_test(test-gtc_vec1 NOT_AVAILABLE)
endif()
