# CMake generated Testfile for 
# Source directory: F:/opengl/glm/test/gtx
# Build directory: F:/opengl/glm/test/gtx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_associated_min_max "F:/opengl/glm/test/gtx/Debug/test-gtx_associated_min_max.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_associated_min_max "F:/opengl/glm/test/gtx/Release/test-gtx_associated_min_max.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_associated_min_max "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_associated_min_max.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_associated_min_max "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_associated_min_max.exe")
else()
  add_test(test-gtx_associated_min_max NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_closest_point "F:/opengl/glm/test/gtx/Debug/test-gtx_closest_point.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_closest_point "F:/opengl/glm/test/gtx/Release/test-gtx_closest_point.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_closest_point "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_closest_point.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_closest_point "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_closest_point.exe")
else()
  add_test(test-gtx_closest_point NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_color_space_YCoCg "F:/opengl/glm/test/gtx/Debug/test-gtx_color_space_YCoCg.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_color_space_YCoCg "F:/opengl/glm/test/gtx/Release/test-gtx_color_space_YCoCg.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_color_space_YCoCg "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_color_space_YCoCg.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_color_space_YCoCg "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_color_space_YCoCg.exe")
else()
  add_test(test-gtx_color_space_YCoCg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_color_space "F:/opengl/glm/test/gtx/Debug/test-gtx_color_space.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_color_space "F:/opengl/glm/test/gtx/Release/test-gtx_color_space.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_color_space "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_color_space.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_color_space "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_color_space.exe")
else()
  add_test(test-gtx_color_space NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_common "F:/opengl/glm/test/gtx/Debug/test-gtx_common.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_common "F:/opengl/glm/test/gtx/Release/test-gtx_common.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_common "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_common.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_common "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_common.exe")
else()
  add_test(test-gtx_common NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_compatibility "F:/opengl/glm/test/gtx/Debug/test-gtx_compatibility.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_compatibility "F:/opengl/glm/test/gtx/Release/test-gtx_compatibility.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_compatibility "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_compatibility.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_compatibility "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_compatibility.exe")
else()
  add_test(test-gtx_compatibility NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_component_wise "F:/opengl/glm/test/gtx/Debug/test-gtx_component_wise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_component_wise "F:/opengl/glm/test/gtx/Release/test-gtx_component_wise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_component_wise "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_component_wise.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_component_wise "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_component_wise.exe")
else()
  add_test(test-gtx_component_wise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_euler_angle "F:/opengl/glm/test/gtx/Debug/test-gtx_euler_angle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_euler_angle "F:/opengl/glm/test/gtx/Release/test-gtx_euler_angle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_euler_angle "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_euler_angle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_euler_angle "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_euler_angle.exe")
else()
  add_test(test-gtx_euler_angle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_extend "F:/opengl/glm/test/gtx/Debug/test-gtx_extend.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_extend "F:/opengl/glm/test/gtx/Release/test-gtx_extend.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_extend "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_extend.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_extend "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_extend.exe")
else()
  add_test(test-gtx_extend NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_extented_min_max "F:/opengl/glm/test/gtx/Debug/test-gtx_extented_min_max.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_extented_min_max "F:/opengl/glm/test/gtx/Release/test-gtx_extented_min_max.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_extented_min_max "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_extented_min_max.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_extented_min_max "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_extented_min_max.exe")
else()
  add_test(test-gtx_extented_min_max NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_fast_exponential "F:/opengl/glm/test/gtx/Debug/test-gtx_fast_exponential.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_fast_exponential "F:/opengl/glm/test/gtx/Release/test-gtx_fast_exponential.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_fast_exponential "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_fast_exponential.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_fast_exponential "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_fast_exponential.exe")
else()
  add_test(test-gtx_fast_exponential NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_fast_square_root "F:/opengl/glm/test/gtx/Debug/test-gtx_fast_square_root.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_fast_square_root "F:/opengl/glm/test/gtx/Release/test-gtx_fast_square_root.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_fast_square_root "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_fast_square_root.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_fast_square_root "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_fast_square_root.exe")
else()
  add_test(test-gtx_fast_square_root NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_fast_trigonometry "F:/opengl/glm/test/gtx/Debug/test-gtx_fast_trigonometry.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_fast_trigonometry "F:/opengl/glm/test/gtx/Release/test-gtx_fast_trigonometry.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_fast_trigonometry "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_fast_trigonometry.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_fast_trigonometry "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_fast_trigonometry.exe")
else()
  add_test(test-gtx_fast_trigonometry NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_gradient_paint "F:/opengl/glm/test/gtx/Debug/test-gtx_gradient_paint.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_gradient_paint "F:/opengl/glm/test/gtx/Release/test-gtx_gradient_paint.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_gradient_paint "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_gradient_paint.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_gradient_paint "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_gradient_paint.exe")
else()
  add_test(test-gtx_gradient_paint NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_handed_coordinate_space "F:/opengl/glm/test/gtx/Debug/test-gtx_handed_coordinate_space.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_handed_coordinate_space "F:/opengl/glm/test/gtx/Release/test-gtx_handed_coordinate_space.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_handed_coordinate_space "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_handed_coordinate_space.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_handed_coordinate_space "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_handed_coordinate_space.exe")
else()
  add_test(test-gtx_handed_coordinate_space NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_integer "F:/opengl/glm/test/gtx/Debug/test-gtx_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_integer "F:/opengl/glm/test/gtx/Release/test-gtx_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_integer "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_integer.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_integer "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_integer.exe")
else()
  add_test(test-gtx_integer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_intersect "F:/opengl/glm/test/gtx/Debug/test-gtx_intersect.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_intersect "F:/opengl/glm/test/gtx/Release/test-gtx_intersect.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_intersect "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_intersect.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_intersect "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_intersect.exe")
else()
  add_test(test-gtx_intersect NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_io "F:/opengl/glm/test/gtx/Debug/test-gtx_io.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_io "F:/opengl/glm/test/gtx/Release/test-gtx_io.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_io "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_io.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_io "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_io.exe")
else()
  add_test(test-gtx_io NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_log_base "F:/opengl/glm/test/gtx/Debug/test-gtx_log_base.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_log_base "F:/opengl/glm/test/gtx/Release/test-gtx_log_base.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_log_base "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_log_base.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_log_base "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_log_base.exe")
else()
  add_test(test-gtx_log_base NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_cross_product "F:/opengl/glm/test/gtx/Debug/test-gtx_matrix_cross_product.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_cross_product "F:/opengl/glm/test/gtx/Release/test-gtx_matrix_cross_product.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_cross_product "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_matrix_cross_product.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_cross_product "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_cross_product.exe")
else()
  add_test(test-gtx_matrix_cross_product NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_decompose "F:/opengl/glm/test/gtx/Debug/test-gtx_matrix_decompose.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_decompose "F:/opengl/glm/test/gtx/Release/test-gtx_matrix_decompose.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_decompose "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_matrix_decompose.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_decompose "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_decompose.exe")
else()
  add_test(test-gtx_matrix_decompose NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_interpolation "F:/opengl/glm/test/gtx/Debug/test-gtx_matrix_interpolation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_interpolation "F:/opengl/glm/test/gtx/Release/test-gtx_matrix_interpolation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_interpolation "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_matrix_interpolation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_interpolation "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_interpolation.exe")
else()
  add_test(test-gtx_matrix_interpolation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_major_storage "F:/opengl/glm/test/gtx/Debug/test-gtx_matrix_major_storage.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_major_storage "F:/opengl/glm/test/gtx/Release/test-gtx_matrix_major_storage.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_major_storage "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_matrix_major_storage.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_major_storage "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_major_storage.exe")
else()
  add_test(test-gtx_matrix_major_storage NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_operation "F:/opengl/glm/test/gtx/Debug/test-gtx_matrix_operation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_operation "F:/opengl/glm/test/gtx/Release/test-gtx_matrix_operation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_operation "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_matrix_operation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_operation "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_operation.exe")
else()
  add_test(test-gtx_matrix_operation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_query "F:/opengl/glm/test/gtx/Debug/test-gtx_matrix_query.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_query "F:/opengl/glm/test/gtx/Release/test-gtx_matrix_query.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_query "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_matrix_query.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_query "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_query.exe")
else()
  add_test(test-gtx_matrix_query NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_transform_2d "F:/opengl/glm/test/gtx/Debug/test-gtx_matrix_transform_2d.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_transform_2d "F:/opengl/glm/test/gtx/Release/test-gtx_matrix_transform_2d.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_transform_2d "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_matrix_transform_2d.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_transform_2d "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_transform_2d.exe")
else()
  add_test(test-gtx_matrix_transform_2d NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_multiple "F:/opengl/glm/test/gtx/Debug/test-gtx_multiple.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_multiple "F:/opengl/glm/test/gtx/Release/test-gtx_multiple.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_multiple "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_multiple.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_multiple "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_multiple.exe")
else()
  add_test(test-gtx_multiple NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_norm "F:/opengl/glm/test/gtx/Debug/test-gtx_norm.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_norm "F:/opengl/glm/test/gtx/Release/test-gtx_norm.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_norm "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_norm.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_norm "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_norm.exe")
else()
  add_test(test-gtx_norm NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_normal "F:/opengl/glm/test/gtx/Debug/test-gtx_normal.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_normal "F:/opengl/glm/test/gtx/Release/test-gtx_normal.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_normal "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_normal.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_normal "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_normal.exe")
else()
  add_test(test-gtx_normal NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_normalize_dot "F:/opengl/glm/test/gtx/Debug/test-gtx_normalize_dot.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_normalize_dot "F:/opengl/glm/test/gtx/Release/test-gtx_normalize_dot.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_normalize_dot "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_normalize_dot.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_normalize_dot "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_normalize_dot.exe")
else()
  add_test(test-gtx_normalize_dot NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_number_precision "F:/opengl/glm/test/gtx/Debug/test-gtx_number_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_number_precision "F:/opengl/glm/test/gtx/Release/test-gtx_number_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_number_precision "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_number_precision.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_number_precision "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_number_precision.exe")
else()
  add_test(test-gtx_number_precision NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_orthonormalize "F:/opengl/glm/test/gtx/Debug/test-gtx_orthonormalize.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_orthonormalize "F:/opengl/glm/test/gtx/Release/test-gtx_orthonormalize.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_orthonormalize "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_orthonormalize.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_orthonormalize "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_orthonormalize.exe")
else()
  add_test(test-gtx_orthonormalize NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_optimum_pow "F:/opengl/glm/test/gtx/Debug/test-gtx_optimum_pow.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_optimum_pow "F:/opengl/glm/test/gtx/Release/test-gtx_optimum_pow.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_optimum_pow "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_optimum_pow.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_optimum_pow "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_optimum_pow.exe")
else()
  add_test(test-gtx_optimum_pow NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_perpendicular "F:/opengl/glm/test/gtx/Debug/test-gtx_perpendicular.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_perpendicular "F:/opengl/glm/test/gtx/Release/test-gtx_perpendicular.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_perpendicular "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_perpendicular.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_perpendicular "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_perpendicular.exe")
else()
  add_test(test-gtx_perpendicular NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_polar_coordinates "F:/opengl/glm/test/gtx/Debug/test-gtx_polar_coordinates.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_polar_coordinates "F:/opengl/glm/test/gtx/Release/test-gtx_polar_coordinates.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_polar_coordinates "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_polar_coordinates.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_polar_coordinates "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_polar_coordinates.exe")
else()
  add_test(test-gtx_polar_coordinates NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_projection "F:/opengl/glm/test/gtx/Debug/test-gtx_projection.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_projection "F:/opengl/glm/test/gtx/Release/test-gtx_projection.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_projection "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_projection.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_projection "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_projection.exe")
else()
  add_test(test-gtx_projection NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_quaternion "F:/opengl/glm/test/gtx/Debug/test-gtx_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_quaternion "F:/opengl/glm/test/gtx/Release/test-gtx_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_quaternion "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_quaternion "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_quaternion.exe")
else()
  add_test(test-gtx_quaternion NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_dual_quaternion "F:/opengl/glm/test/gtx/Debug/test-gtx_dual_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_dual_quaternion "F:/opengl/glm/test/gtx/Release/test-gtx_dual_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_dual_quaternion "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_dual_quaternion.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_dual_quaternion "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_dual_quaternion.exe")
else()
  add_test(test-gtx_dual_quaternion NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_range "F:/opengl/glm/test/gtx/Debug/test-gtx_range.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_range "F:/opengl/glm/test/gtx/Release/test-gtx_range.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_range "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_range.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_range "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_range.exe")
else()
  add_test(test-gtx_range NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_rotate_normalized_axis "F:/opengl/glm/test/gtx/Debug/test-gtx_rotate_normalized_axis.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_rotate_normalized_axis "F:/opengl/glm/test/gtx/Release/test-gtx_rotate_normalized_axis.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_rotate_normalized_axis "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_rotate_normalized_axis.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_rotate_normalized_axis "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_rotate_normalized_axis.exe")
else()
  add_test(test-gtx_rotate_normalized_axis NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_rotate_vector "F:/opengl/glm/test/gtx/Debug/test-gtx_rotate_vector.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_rotate_vector "F:/opengl/glm/test/gtx/Release/test-gtx_rotate_vector.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_rotate_vector "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_rotate_vector.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_rotate_vector "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_rotate_vector.exe")
else()
  add_test(test-gtx_rotate_vector NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_scalar_multiplication "F:/opengl/glm/test/gtx/Debug/test-gtx_scalar_multiplication.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_scalar_multiplication "F:/opengl/glm/test/gtx/Release/test-gtx_scalar_multiplication.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_scalar_multiplication "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_scalar_multiplication.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_scalar_multiplication "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_scalar_multiplication.exe")
else()
  add_test(test-gtx_scalar_multiplication NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_scalar_relational "F:/opengl/glm/test/gtx/Debug/test-gtx_scalar_relational.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_scalar_relational "F:/opengl/glm/test/gtx/Release/test-gtx_scalar_relational.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_scalar_relational "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_scalar_relational.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_scalar_relational "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_scalar_relational.exe")
else()
  add_test(test-gtx_scalar_relational NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_simd_vec4 "F:/opengl/glm/test/gtx/Debug/test-gtx_simd_vec4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_simd_vec4 "F:/opengl/glm/test/gtx/Release/test-gtx_simd_vec4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_simd_vec4 "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_simd_vec4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_simd_vec4 "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_simd_vec4.exe")
else()
  add_test(test-gtx_simd_vec4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_simd_mat4 "F:/opengl/glm/test/gtx/Debug/test-gtx_simd_mat4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_simd_mat4 "F:/opengl/glm/test/gtx/Release/test-gtx_simd_mat4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_simd_mat4 "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_simd_mat4.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_simd_mat4 "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_simd_mat4.exe")
else()
  add_test(test-gtx_simd_mat4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_spline "F:/opengl/glm/test/gtx/Debug/test-gtx_spline.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_spline "F:/opengl/glm/test/gtx/Release/test-gtx_spline.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_spline "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_spline.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_spline "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_spline.exe")
else()
  add_test(test-gtx_spline NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_string_cast "F:/opengl/glm/test/gtx/Debug/test-gtx_string_cast.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_string_cast "F:/opengl/glm/test/gtx/Release/test-gtx_string_cast.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_string_cast "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_string_cast.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_string_cast "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_string_cast.exe")
else()
  add_test(test-gtx_string_cast NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_type_aligned "F:/opengl/glm/test/gtx/Debug/test-gtx_type_aligned.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_type_aligned "F:/opengl/glm/test/gtx/Release/test-gtx_type_aligned.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_type_aligned "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_type_aligned.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_type_aligned "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_type_aligned.exe")
else()
  add_test(test-gtx_type_aligned NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_vector_angle "F:/opengl/glm/test/gtx/Debug/test-gtx_vector_angle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_vector_angle "F:/opengl/glm/test/gtx/Release/test-gtx_vector_angle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_vector_angle "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_vector_angle.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_vector_angle "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_vector_angle.exe")
else()
  add_test(test-gtx_vector_angle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_vector_query "F:/opengl/glm/test/gtx/Debug/test-gtx_vector_query.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_vector_query "F:/opengl/glm/test/gtx/Release/test-gtx_vector_query.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_vector_query "F:/opengl/glm/test/gtx/MinSizeRel/test-gtx_vector_query.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_vector_query "F:/opengl/glm/test/gtx/RelWithDebInfo/test-gtx_vector_query.exe")
else()
  add_test(test-gtx_vector_query NOT_AVAILABLE)
endif()
